package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/hoshina-dev/gapi/internal/adapters/graph/model"
	"github.com/hoshina-dev/gapi/internal/core/domain"
)

// Geometry is the resolver for the geometry field.
func (r *adminAreaResolver) Geometry(ctx context.Context, obj *domain.AdminArea) (map[string]any, error) {
	var geom map[string]any
	if err := json.Unmarshal(obj.Geometry, &geom); err != nil {
		return nil, err
	}
	return geom, nil
}

// AdminAreas is the resolver for the adminAreas field.
func (r *queryResolver) AdminAreas(ctx context.Context, adminLevel int32, tolerance *float64) ([]*domain.AdminArea, error) {
	validTolerance, err := validateTolerance(tolerance)
	if err != nil {
		return nil, err
	}
	return r.adminAreaService.GetAll(ctx, adminLevel, validTolerance)
}

// AdminArea is the resolver for the adminArea field.
func (r *queryResolver) AdminArea(ctx context.Context, id string, adminLevel int32, tolerance *float64) (*domain.AdminArea, error) {
	validTolerance, err := validateTolerance(tolerance)
	if err != nil {
		return nil, err
	}
	id_int, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	return r.adminAreaService.GetByID(ctx, id_int, adminLevel, validTolerance)
}

// AdminAreaByCode is the resolver for the adminAreaByCode field.
func (r *queryResolver) AdminAreaByCode(ctx context.Context, code string, adminLevel int32, tolerance *float64) (*domain.AdminArea, error) {
	validTolerance, err := validateTolerance(tolerance)
	if err != nil {
		return nil, err
	}
	return r.adminAreaService.GetByCode(ctx, code, adminLevel, validTolerance)
}

// ChildrenByCode is the resolver for the childrenByCode field.
func (r *queryResolver) ChildrenByCode(ctx context.Context, parentCode string, childLevel int32, tolerance *float64) ([]*domain.AdminArea, error) {
	validTolerance, err := validateTolerance(tolerance)
	if err != nil {
		return nil, err
	}
	return r.adminAreaService.GetChildren(ctx, parentCode, childLevel, validTolerance)
}

// FilterCoordinatesByBoundary is the resolver for the filterCoordinatesByBoundary field.
func (r *queryResolver) FilterCoordinatesByBoundary(ctx context.Context, coordinates []*model.CoordinateInput, boundaryID string) ([][]float64, error) {
	// Parse and validate boundary ID
	boundaryInfo, err := parseBoundaryID(boundaryID)
	if err != nil {
		return nil, err
	}

	// Validate coordinates
	if err := validateCoordinates(coordinates); err != nil {
		return nil, err
	}

	// Convert CoordinateInput to service layer format
	coords := make([][2]float64, len(coordinates))
	for i, coord := range coordinates {
		coords[i] = [2]float64{coord.Lat, coord.Lon}
	}

	// Call service layer
	return r.adminAreaService.FilterCoordinatesByBoundary(
		ctx,
		coords,
		boundaryInfo.GIDValue,
		boundaryInfo.AdminLevel,
	)
}

// AdminArea returns AdminAreaResolver implementation.
func (r *Resolver) AdminArea() AdminAreaResolver { return &adminAreaResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type adminAreaResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
