package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hoshina-dev/gapi/internal/core/domain"
)

// AdminAreas is the resolver for the adminAreas field.
func (r *queryResolver) AdminAreas(ctx context.Context, adminLevel int32) ([]*domain.AdminArea, error) {
	return r.adminAreaService.GetAll(ctx, adminLevel)
}

// AdminArea is the resolver for the adminArea field.
func (r *queryResolver) AdminArea(ctx context.Context, id string, adminLevel int32) (*domain.AdminArea, error) {
	id_int, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	return r.adminAreaService.GetByID(ctx, id_int, adminLevel)
}

// AdminAreaByCode is the resolver for the adminAreaByCode field.
func (r *queryResolver) AdminAreaByCode(ctx context.Context, code string, adminLevel int32) (*domain.AdminArea, error) {
	return r.adminAreaService.GetByCode(ctx, code, adminLevel)
}

// ChildrenByCode is the resolver for the childrenByCode field.
func (r *queryResolver) ChildrenByCode(ctx context.Context, parentCode string, childLevel int32) ([]*domain.AdminArea, error) {
	panic(fmt.Errorf("not implemented: ChildrenByCode - childrenByCode"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
