// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Coordinate struct {
	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`
}

type CoordinateInput struct {
	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`
}

type Query struct {
}
