// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CoordinateInput struct {
	ID  string  `json:"id"`
	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`
}

type Query struct {
}
